dist: xenial
language: node_js
node_js:
  - "10"
  - "12"
script:
  - make
after_success:
  - make report-coverage
deploy:
  on: 
    tags: true
  provider: npm
  tag: next
  email: dmuino@gmail.com
  api_key:
    secure: "HM4kqTyYwH7DeveozWG2j2CiPC+CXOun0EzNfVYPvrIanNiFIdxM5N428z4ifyErR0ORxLzly8V9Gmppz9Hl4R1foek5pTpwKHmwfEQDM6Tzoer8fS5HfbosZ9Qxc3iNDgwt/sdnLtu4Zo5Qq85upl7DokHd3aiJh1XOo6V/JYNBdbGGbutYuEfNxc5upGq1zF2Y/9ZXxjhIQTQXkxzMW8DDqGtcibWqKBh6kavNh35baVDZ72R+zY/x51A/wD1RF3hxmiVcAlTQdqsKFdXNw3LrFDvbcCvnzarWWrtzJnzaaj7pzlm9Q4QXbk9Ro5/oh23fyiVDBjfqfLsornhM0HdIGEryoy8k27QH0iD76pkU5oK4fJwTeOEmteaG0ZkslkW3j2ufdho8qMicN/3e2vZpH/hk0gMPt7K/4/k6QTvN1amRHFmHLClVnP0O6AbdFncy803Ss9S5WfixDly4D+6n8i04PuYZR7+gBpkqsSyvC/n3csAQNyScIAuPLs2Kv9IOPmoW1on49xyrc+HypB+t7Goo4U9gXD++pMMMa2LUm73XKyjCgdWtYEC+1U5j3UMO7I2VqL1UlkExkmYlk/Qi6iTYS5FgAoHR1WKvmW62iMjTAJ2aKoAyCva2JVdMHlQp+XGwgqrrnYcHXrKdUsGoM5tPwFER0jky5DkkBfg="
