dist: xenial
language: node_js
node_js:
- '10'
- '12'
- '14'
script:
- make
after_success:
- make report-coverage
deploy:
  on:
    tags: true
    node_js: '12'
  provider: npm
  tag: next
  email: dmuino@gmail.com
  api_key:
    secure: rrdc13iVNB+835UvznhptERn3rcP8Uf7V+OsTj2mVmhTSvqfO2WW7PIvODjYYcYCYSQpKd2u3lpRp/sS2hfnTJUanQTiiNVlWsYGC6zoM+jsHbajGQyP7Hie7yN40kdMsWwlwrdmEzyx/LsIuw3rifp0agodJ8g50o2XR16p7hJYdaU2+wh6zRNEE9nebtzFNelHjqzuiQMW4qCk3EgwjVJj7qWaTMSoHBIRyWQ3zS737Ndo5mLwJPsE15OFL++YnPiMpkh8dXLaCPm4YMkVXetz+WEYAe6Yofhw/pYpy55qVgGE+a4LaW4Q2HhCfLeHHYdsN0m8kLn34wHPZ1sHJcDMF91MoEF4FAu3lT0Gjd/MNBqbasT0iSeu3NiICBRIj+WfrTe7l6mgojaicJWxcB78jwKNA60JoRAuozknd6+azTDgmbgIrMPaato09b3R9GDUt6HB0kkfOf85RjSqNE7BzGFsjgQBpwljNfO/PtnrGq05x79ejbpXHgAMi2Srk59W5K4S5jIIUaLM/a6/QFqRDFfPJKRz5xYzHy9gUSAmSbMS0N9q3ja5FdfF8IlyPdcQyXAwH0QrTrJE8T4EyKU6JTBpOS9EjH09X7QPN4Ff8ovQEhjUwq2axJqHQwH3jUnAHPfkNdejdi9rEoqUmAfvkDJDBNxb/2athZd4c5Q=
