dist: xenial
language: node_js
node_js:
- '10'
- '12'
- '14'
- '16'
script:
- make
deploy:
  on:
    tags: true
    node_js: '12'
  provider: npm
  tag: next
  email: dmuino@gmail.com
  api_key:
    secure: WCNnJn0DGA0H+RcwEPmgdKFkibNwIOBEUF+goCS6WZKmog16uoSwllDmg7MJrTzdPER4ruPKiLNUQQoFPO6zG7R4dTNvbEJM+ZamKpS8PT6IFyW5D/rQB+Id1Y6Q6DCQK2e81HGyyxnBKRLlUPwUZuSB7g/U5EwxEG1tpyvEjxYPavXIDh83IJOtK2T1NT96IueCW4vdfOe+pb+veWyvk1B/4G5ciw3QaK1GbwpAp/IwFMG4o4Zovsdj996AR+zhKzsQuy1wIRGN1xuEVEv+G7PdEi+826zB1hNcRLm9Iqa+e/DTqhpo17XSTCpfzD6J1AkFVmwgdM3RMaeIcFvqTYDuulM23UAzbM5FIdxnVkW7SvRRIRGtq1UOigdta2oSyhoqT8t9VkNt3iBNgYbT3Y1DXMJLftlyHWFuN8p9kB2mglYGJaJmzA9NK9Nl1eOU0/uFNe3vV7OV+HVH5cW3zCCtr/pWjEyeZXaxjbEOHM+quG6cSAQZMFejNILCsW97eVspL7DjzsiHPe0wPp0GUqk7lzGVMRBOKApvZ9ljQUQVsM5MnZJYe9PYMxjfwGe6ntHv7TsQbaF51YWkoeQ8AKSbWLgqTP4tZhLBG0Be5Gx5i90MNr0kNoFsOsvgIhFLYKd6k2ZeJbqttdCWi71WLtVk4m/PmzZyl3CHGc0J0FY=
